"use client";

import { motion } from "framer-motion";
import {
    Dumbbell,
    Calculator,
    Utensils,
    Calendar,
    MessageCircle,
    CreditCard,
    Sparkles,
    Target
} from "lucide-react";
import Link from "next/link";

const features = [
    {
        icon: <Calendar className="w-6 h-6" />,
        title: "Gym Schedule",
        description: "Check our daily workout timings and plan your sessions.",
        link: "#protocol",
        color: "text-blue-400"
    },
    {
        icon: <Dumbbell className="w-6 h-6" />,
        title: "Exercise Library",
        description: "800+ exercises with videos and instructions.",
        link: "/workouts",
        color: "text-green-400"
    },
    {
        icon: <Utensils className="w-6 h-6" />,
        title: "AI Diet Planner",
        description: "Get a personalized diet plan generated by AI.",
        link: "/fuel",
        color: "text-orange-400"
    },
    {
        icon: <Calculator className="w-6 h-6" />,
        title: "Fitness Calculators",
        description: "Calculate your BMI, TDEE, and 1 Rep Max.",
        link: "/calculators",
        color: "text-purple-400"
    },
    {
        icon: <CreditCard className="w-6 h-6" />,
        title: "Membership Pricing",
        description: "View our flexible membership plans.",
        link: "/pricing",
        color: "text-yellow-400"
    },
    {
        icon: <MessageCircle className="w-6 h-6" />,
        title: "Contact Us",
        description: "Get in touch or visit our gym.",
        link: "/contact",
        color: "text-pink-400"
    }
];

export default function FeaturesOverview() {
    return (
        <section className="py-16 md:py-24 bg-black">
            <div className="max-w-6xl mx-auto px-4">
                {/* Header */}
                <motion.div
                    className="text-center mb-12"
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                >
                    <div className="flex items-center justify-center gap-2 mb-4">
                        <Sparkles className="w-5 h-5 text-gym-red" />
                        <span className="text-xs uppercase tracking-widest text-gray-400 font-mono">
                            Welcome to Gym Sphere
                        </span>
                        <Sparkles className="w-5 h-5 text-gym-red" />
                    </div>
                    <h2 className="text-3xl md:text-5xl font-black uppercase mb-4">
                        What Can You Do Here?
                    </h2>
                    <p className="text-gray-400 max-w-2xl mx-auto">
                        Gym Sphere is more than just a gym. We provide tools to help you
                        train smarter, eat better, and track your progress, all in one place.
                    </p>
                </motion.div>

                {/* Feature Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {features.map((feature, index) => (
                        <motion.div
                            key={feature.title}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: index * 0.1 }}
                        >
                            {feature.link ? (
                                <Link href={feature.link} className="block h-full">
                                    <FeatureCard feature={feature} />
                                </Link>
                            ) : (
                                <FeatureCard feature={feature} />
                            )}
                        </motion.div>
                    ))}
                </div>

                {/* CTA */}
                <motion.div
                    className="text-center mt-12"
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.5 }}
                >
                    <div className="inline-flex items-center gap-2 bg-gym-red/10 border border-gym-red/30 px-6 py-3 rounded-full">
                        <Target className="w-5 h-5 text-gym-red" />
                        <span className="text-sm font-bold uppercase tracking-wide">
                            Start Your Transformation Today
                        </span>
                    </div>
                </motion.div>
            </div>
        </section>
    );
}

function FeatureCard({ feature }: { feature: typeof features[0] }) {
    return (
        <div className={`h-full p-6 bg-white/5 border border-white/10 rounded-xl hover:border-gym-red/50 hover:bg-white/[0.07] transition-all group ${feature.link ? 'cursor-pointer' : ''}`}>
            <div className={`w-12 h-12 rounded-lg bg-white/10 flex items-center justify-center mb-4 ${feature.color} group-hover:scale-110 transition-transform`}>
                {feature.icon}
            </div>
            <h3 className="text-xl font-bold mb-2 group-hover:text-gym-red transition-colors">
                {feature.title}
            </h3>
            <p className="text-gray-400 text-sm">
                {feature.description}
            </p>
            {feature.link && (
                <p className="text-gym-red text-xs uppercase tracking-widest mt-4 font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                    Explore →
                </p>
            )}
        </div>
    );
}
